blank_issues_enabled: false
contact_links:
  - name: Questions / ideas
    url: https://github.com/bthornemail/UniversalLifeProtocol/discussions
    about: Start a discussion for general questions or brainstorming
