packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/avatar-console'
  - 'apps/universe-graph'
  - 'mcp-integration'
  - 'sacred-geometry-harmony'
  - 'scripts'
  - 'autonomous-observer'
  - 'packages/avatar-gate'
